### ISSUE TITLE
Sinopia fails to start if github config is not specified

### ISSUE THREAD

**Issue by fastest963** [fl4re/sinopia#8]
If you don't specify a `github` dict in the yaml then the application doesn't start since github_wrapper does `config.application_name` but config is undefined. If you don't have a `github` or `google` dict then maybe those plugins should just be disabled?

**Comment by dgaya** [comment]
Can you try now ?
Remember to remove the ./auth/github entry in config.yaml, as well.

**Comment by fastest963** [comment]
Works now. Thanks!
